#!/usr/bin/python3
# sys lib to ret the args
import sys


# this func will the fact unleach
def get_fact():
    """
    this function will convert num to this n=p*q
    """
    try:
        modfact = sys.argv[1]
        with open(modfact) as f:
            for modconv in f:
                modconv = int(modconv)
                if modconv % 2 == 0:
                        print("{}={}*{}".format(modconv, modconv // 2, 2))
                        continue
                i = 3
                while i < modconv // 2:
                    if modconv % i == 0:
                        print("{}={}*{}".format(modconv, modconv // i, i))
                        break
                    i = i + 2
                if i == (modconv // 2) + 1:
                    print("{}={}*{}".format(modconv, modconv, 1))
    except (IndexError):
        pass


# run the prog
get_fact()